### ISSUE TITLE
new function for B525

### ISSUE THREAD

**Issue by wep777** [jinxo13/HuaweiB525Router#3]
DeviceName B525s-23a
HardwareVersion WL1B520FM

#
# SWITCH ETH to 4G #
#
`
request = '<?xml version="1.0" encoding="UTF-8"?><request><connectionmode>5</connectionmode></request>'
`
`
response = router.api('cradle/basic-info', request)
`
#
# SWITCH 4G to ETH #
#
`
request = '<?xml version="1.0" encoding="UTF-8"?><request><connectionmode>0</connectionmode></request>'
`
`
response = router.api('cradle/basic-info', request)
`

**Comment by jinxo13** [comment]
Thanks @wep777, I've added this into the API.
router.ethernet.set_auto()
router.ethernet.set_lan_only()
router.ethernet.set_ppoe()
router.ethernet.set_dynamic()
etc...

I added support for all the settings I found, but haven't been able to test it all, as I'm only using 4G at the moment.

If you get a chance to test any of them let me know.

**Comment by bfg100k** [comment]
Thanks for this. I was looking high and low for a way to change ETH port 4 to LAN (default is WAN) and router.ethernet.set_lan_only() did the trick for me. Having said that, it wasn't clear to me initially as the comment in the example usage says `#LTE mode - so uses 3G or 4G`. Perhaps it is clearer to say `#LTE mode - so uses 3G or 4G. This also converts port 4 into a LAN port.`?
