### ISSUE TITLE
Call in progress

### ISSUE THREAD

**Issue by cagnulein** [jinxo13/HuaweiB525Router#7]
Is it possible to know when a voice call is in progress? Sometimes i have to switch back manually to 4g beucase the router stays to 3g after a voice call, and i would like to build an automa.

Thanks

**Comment by jinxo13** [comment]
Hi @cagnulein - I had as look through what is available.

It looks like there may be an api call that can help:
```
api/voice/voicebusy
```
It looks like the response is:
```
<response>Idle</response>
```
or
```
<response>Busy</response>
```
Can you try that and see if it works?

**Comment by cagnulein** [comment]
Yes, it works flawless! Thanks man!
